# Generated by Django 2.2.12 on 2020-06-01 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_alignment', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=300)),
                ('button_link', models.URLField(blank=True, help_text='Enter your external URL')),
                ('button_text', models.CharField(max_length=50)),
                ('button_page', models.ForeignKey(blank=True, help_text='Select an internal page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
        ),
    ]
