# Generated by Django 2.2.12 on 2020-06-02 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('basic', '0002_basicpage_footer_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='social_sharing_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
